name: DBT_Pro
version: 1.0.0
config-version: 2

profile: postgres_profile

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

models:
  DBT_Pro:
    +materialized: view
