postgres_profile:
  target: dev
  outputs:
    dev:
      type: postgres
      host: 127.0.0.1
      user: dbt_user
      password: 3757p.A
      port: 5432
      dbname: analytics
      schema: dbt_schema
      threads: 4
      connect_timeout: 30
