postgres_profile:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: 3757p.A
      port: 5432
      dbname: postgres
      schema: Data_Marketing
      threads: 4
      connect_timeout: 30
